import React from "react";
import { Metadata } from "next";
import {
  FileCheck,
  Activity,
  Heart,
  Pill,
  Clock,
  Lock,
  FileText,
  Scale,
  ThumbsUp,
  Stethoscope,
  Calendar,
  LucideIcon,
} from "lucide-react";
import { APP_METADATA } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Terms & Conditions",
  description: "Read the MedAxiz Terms & Conditions to understand user agreements, medication responsibilities, and our disclaimers.",
};

interface TermSection {
  id: string;
  title: string;
  icon: LucideIcon;
  content: string[];
}

export default function TermsAndConditionsPage() {
  const sections: TermSection[] = [
    {
      id: "purpose",
      title: "Purpose of MedAxiz",
      icon: Activity,
      content: [
        `${APP_METADATA.name} is built as a tool to help users manage their medication intake, establish timing schedules, track adherence history, and print summary PDF documents.`,
        "The application is engineered as an offline-first service to safeguard health tracking records. No accounts, cloud databases, or remote trackers are maintained by the developer.",
      ],
    },
    {
      id: "responsibility",
      title: "Medication Responsibility",
      icon: Heart,
      content: [
        "You acknowledge that you are entirely responsible for your own health care, medications, and wellness decisions.",
        "The inputs, medication schedules, dosage amounts, and names entered into the application are configured solely by you. You must verify that the schedules align with your actual medical prescriptions.",
      ],
    },
    {
      id: "dosage-disclaimer",
      title: "Dosage & Usage Disclaimer",
      icon: Pill,
      content: [
        "We are not responsible for any dosage errors, double-dosing, missed dosages, or incorrect medication mixtures entered into the scheduling engine.",
        "Always follow the exact packaging instructions and consult a qualified pharmacist or physician for correct dosage usage, interactions, and precautions.",
      ],
    },
    {
      id: "reminder-accuracy",
      title: "Reminder Accuracy",
      icon: Clock,
      content: [
        "MedAxiz schedules alerts using native operating system tools (such as Android AlarmManager). Alarm reliability can be impacted by device power settings, background restriction policies (e.g. Doze mode, battery savers), system updates, or hardware shutoffs.",
        "We do not guarantee that every alarm will be delivered precisely on time. You should not rely solely on MedAxiz notifications as your single source of truth for critical life-supporting medications.",
      ],
    },
    {
      id: "no-medical-advice",
      title: "No Medical Advice",
      icon: Stethoscope,
      content: [
        "The content, charts, adherence dashboards, and reports generated by the application are for informational purposes only. The application does not contain medical advice.",
        "Nothing in the application is a substitute for professional medical diagnosis, treatment, or advice from a licensed medical professional.",
      ],
    },
    {
      id: "security-privacy",
      title: "Data Security & Privacy",
      icon: Lock,
      content: [
        "Since the application stores all databases locally, physical access to your device determines data access. We recommend enabling the application-level PIN or biometric lock configurations in the settings panel to secure your logs.",
        "We are not responsible for data breaches resulting from physical theft, unencrypted operating system backups, or device compromise.",
      ],
    },
    {
      id: "generated-reports",
      title: "Generated Reports",
      icon: FileText,
      content: [
        "PDF reports generated by the application are compiled based on the local logs entered by the user. You are responsible for verifying the accuracy of these files before sharing them with your doctor, caregiver, or medical provider.",
      ],
    },
    {
      id: "liability",
      title: "Limitation of Liability",
      icon: Scale,
      content: [
        "TO THE MAXIMUM EXTENT PERMITTED BY LAW, MEDAXIZ AND ITS DEVELOPERS SHALL NOT BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENT, OR PUNITIVE DAMAGES, OR LOSS OF HEALTH DATA, ARISING OUT OF THE USE OR INABILITY TO USE THE APPLICATION.",
        "YOU USE THIS TOOL AT YOUR OWN SOLE RISK.",
      ],
    },
    {
      id: "acceptance",
      title: "Acceptance of Terms",
      icon: ThumbsUp,
      content: [
        "By installing, downloading, or using the MedAxiz mobile application, you explicitly agree to accept and abide by these Terms & Conditions and our Privacy Policy.",
        "If you do not agree to these terms, do not install or use the application.",
      ],
    },
  ];

  return (
    <div className="max-w-7xl mx-auto px-4 py-12 sm:px-6 lg:px-8">
      {/* Page Title */}
      <div className="border-b border-slate-200 dark:border-slate-800 pb-8 mb-10">
        <div className="flex items-center space-x-3 text-primary mb-3">
          <FileCheck className="h-8 w-8 stroke-[2]" />
          <span className="font-semibold text-sm uppercase tracking-wider">Legal Framework</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-extrabold text-slate-900 dark:text-white tracking-tight">
          Terms & Conditions
        </h1>
        <div className="flex items-center space-x-2 text-sm text-slate-500 dark:text-slate-400 mt-3">
          <Calendar className="h-4 w-4" />
          <span>Last Updated: June 2026</span>
        </div>
      </div>

      {/* Quick Jump Navigation Panel */}
      <div className="bg-white dark:bg-[#12131a] rounded-2xl border border-slate-200/60 dark:border-slate-800/60 p-6 mb-12 shadow-sm">
        <h2 className="text-sm font-bold text-slate-400 dark:text-slate-500 uppercase tracking-wider mb-4">
          Quick Navigation
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-2">
          {sections.map((section) => (
            <a
              key={section.id}
              href={`#${section.id}`}
              className="text-sm text-slate-600 dark:text-slate-400 hover:text-primary dark:hover:text-primary transition-colors flex items-center gap-1.5 focus:outline-none focus:underline"
            >
              <span className="w-1.5 h-1.5 rounded-full bg-primary" />
              <span>{section.title}</span>
            </a>
          ))}
        </div>
      </div>

      {/* Cards Layout */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {sections.map((section) => {
          const Icon = section.icon;
          return (
            <section
              key={section.id}
              id={section.id}
              className="scroll-mt-24 p-6 bg-white dark:bg-[#12131a] rounded-2xl border border-slate-200/60 dark:border-slate-800/60 shadow-sm hover:shadow-md transition-shadow flex flex-col"
            >
              <div className="flex items-center gap-3.5 mb-4 pb-3 border-b border-slate-100 dark:border-slate-800/40">
                <div className="w-10 h-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center">
                  <Icon className="h-5 w-5 stroke-[2]" />
                </div>
                <h2 className="font-bold text-lg text-slate-900 dark:text-white">
                  {section.title}
                </h2>
              </div>
              <div className="space-y-3 flex-grow">
                {section.content.map((p, idx) => (
                  <p
                    key={idx}
                    className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed"
                  >
                    {p}
                  </p>
                ))}
              </div>
            </section>
          );
        })}
      </div>
    </div>
  );
}
